### ISSUE TITLE
Single Page Guide

### ISSUE THREAD

**Issue by disney7** [AndrewEllis93/Print-Tuning-Guide#23]
Is there an easy/quick way to combine all the guide sections into a single, continuous page? That makes it very easy to search keywords (via browser) as well as just scroll down for the next step, rather than clicking links continuously or jumping browser tabs.

**Comment by AndrewEllis93** [comment]
I actually did the exact opposite of this recently. 

It used to be one monolithic page up until a couple months ago, because section links just don't work. It hops to the linked section, THEN loads all the images, which throws off your page position. 

I preferred it that way too, from a readability perspective, but being able to link people to certain sections/pages is just too important.
