### ISSUE TITLE
Cura flow rate is not the same for each feature

### ISSUE THREAD

**Issue by dewi-ny-je** [AndrewEllis93/Print-Tuning-Guide#67]
I am exceptionally using Cura to calibrate an UM2+ and I followed the EM tuning steps, which I knew already well. I will use here "flow" as Cura means it, instead of "EM".

After printing I found which was the best cube, but then I noticed the flow seemed sometimes too high on the sides (or maybe it was just poor cooling).
Anyway I decided to check further and by displaying the options in "Expert" mode I found that, by default, Cura has "top/bottom flow" to 5% less than the flow shown in the simpler modes.

I think it's because flow on walls is less critical for the appearance (5% of 0.4 mm line width is 20 microns and in fact they have by default horizontal expansion to -0.015 mm!!) but excessive flow on top/bottom will show very easily.

I think you should at least mention it.

The options are:
- set it to the same value as the other flows, since your calibration method allows way higher accuracy than any conventional method, 
- keep it as default (dynamically set to 4% or 5% lower than base flow) because walls won't show any issue and strength will be better 
 
By the way, Cura calculates flow differently from Slic3r derivatives, see https://community.ultimaker.com/topic/28492-flow-calculations/ stating "It assumes the lines are rectangular with a cross sectional area of layer-height * line-width" (this statement matches my memory from reading the same somewhere else) vs https://manual.slic3r.org/advanced/flow-math so maybe higher flow on adjacent lines is actually needed on Cura to fully merge? it should apply also to top/bottom though so I don't know.

Anyway you are the expert, I just laid out all the information I have so you can add the best remark to the page about EM tuning.

**Comment by AndrewEllis93** [comment]
Yes, the flow math is different between Cura and Slic3r derivatives. The flow rate formulas given in the guide are those that Cura uses, which are much simpler and still generally "close enough" to use for estimation with Slic3r derivatives.

Slic3r calculates cross-sectional area using [this formula](https://ellis3dp.com/Print-Tuning-Guide/articles/misconceptions.html#you-shouldnt-tune-extrusion-multiplier-the-slicer-knows-best), rather than the simpler LW * LH formula that Cura uses. That multiplied by speed gives the volumetric flow rate. There's some more fun math on that page if you're interested.
I actually much prefer Cura's, for the record, but that's a whole spiel.

I'm looking at my Cura instance, and it has top/bottom flow set to 100% for all of mine. I added the UM2+ and it is indeed set to 95%. Not sure why it differs between printers like that. I'll make a note.
